### ISSUE TITLE
Uninitialized constant Kcu::Deploys::GetConfig::YAML on v0.8.0

### ISSUE THREAD

**Issue by iamajvillalobos** [bloom-solutions/kcu#9]
I'm getting an error when I try to run the command `kcu deploy staging_03` for version `0.8.0`. I tried to uninstall and install the last version which `0.7.0` and I can deploy again properly. It looks like it's not finding the `kcu.yml` file even though I'm running it from the root of the project.

```
website staging_03 $ kcu deploy staging_03 --trace
Traceback (most recent call last):
        22: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/bin/kcu:23:in `<main>'
        21: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/bin/kcu:23:in `load'
        20: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/kcu-0.8.0/bin/kcu:11:in `<top (required)>'
        19: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/kcu-0.8.0/lib/kcu/client.rb:52:in `run'
        18: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/delegates.rb:15:in `run!'
        17: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/runner.rb:68:in `run!'
        16: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/runner.rb:446:in `run_active_command'
        15: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/command.rb:153:in `run'
        14: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/commander-4.4.4/lib/commander/command.rb:178:in `call'
        13: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/kcu-0.8.0/lib/kcu/client.rb:48:in `block (2 levels) in run'
        12: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/kcu-0.8.0/lib/kcu/actions/deploy_action.rb:11:in `call'
        11: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/organizer/with_reducer_log_decorator.rb:33:in `reduce'
        10: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/organizer/with_reducer.rb:20:in `reduce'
         9: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/organizer/with_reducer.rb:20:in `reduce'
         8: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/organizer/with_reducer.rb:20:in `each'
         7: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/organizer/with_reducer.rb:22:in `block in reduce'
         6: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/organizer/with_reducer.rb:49:in `invoke_action'
         5: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/action.rb:41:in `block in executed'
         4: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/context/key_verifier.rb:49:in `verify_keys'
         3: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/action.rb:44:in `block (2 levels) in executed'
         2: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/action.rb:44:in `catch'
         1: from /Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/light-service-0.8.3/lib/light-service/action.rb:45:in `block (3 levels) in executed'
/Users/ajvillalobos/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/kcu-0.8.0/lib/kcu/services/deploys/get_config.rb:13:in `block in <class:GetConfig>': uninitialized constant Kcu::Deploys::GetConfig::YAML (NameError)
website staging_03 $
```

**Comment by ramontayag** [comment]
Ah, I think the file we removed included yaml for us. So we probably just need to require yaml

**Comment by ramontayag** [comment]
Closing - this has been resolved.
